using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace CybersecurityAwarenessBot
{

    // A delegate used to modify the tone of the bot's response dynamically based on user sentiment.

    public delegate string SentimentModifier(string botResponse);


    // Defines the current operational mode of the Bot Engine.

    public enum BotState { Normal, QuizActive }


    // The core logical brain of the application. 
    // Processes Natural Language Processing (NLP), maintains conversation state, and handles the Quiz mechanics.

    public class BotEngine
    {
        // --- PUBLIC PROPERTIES ---
        public string UserName { get; set; } = "User";

        // Exposes the current quiz state so the UI knows when to disable the text box and show buttons
        public bool IsQuizActive => _currentState == BotState.QuizActive;

        // --- PRIVATE FIELDS ---
        private BotState _currentState = BotState.Normal;
        private DatabaseHelper _dbHelper;
        private Random _randomizer; // Used to pick random responses so the bot feels more human
        private List<string> _activityLog; // In-memory volatile cache for the current session's actions

        // Quiz State Tracking Variables
        private int _quizScore = 0;
        private int _currentQuestionIndex = 0;
        private List<QuizQuestion> _quizQuestions;

        // Knowledge Base: Maps a keyword (e.g., "phishing") to a list of potential responses
        private readonly Dictionary<string, List<string>> _topicResponses;

    
        // Initializes a new instance of the BotEngine, setting up data structures,
        // database connections, and the internal knowledge base.
    
        public BotEngine()
        {
            _randomizer = new Random();
            _activityLog = new List<string>();
            _quizQuestions = new List<QuizQuestion>();
            _dbHelper = new DatabaseHelper();

            LogActivity("Application started. BotEngine initialized.");

            // StringComparer.OrdinalIgnoreCase ensures that "PASSWORD", "password", and "PassWord" all trigger the same response
            _topicResponses = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase)
            {
                { "password", new List<string> { "Make sure to use strong, unique passwords for each account.", "Consider using a password manager." } },
                { "phishing", new List<string> { "Never click on unexpected links in SMSes or emails.", "Look out for spelling errors in emails." } },
                { "scam", new List<string> { "If an online deal looks too good to be true, it probably is.", "Never share your OTP with anyone." } },
                { "privacy", new List<string> { "Check your social media settings to ensure your profile is private.", "Avoid sharing your real-time location." } }
            };

            // Populate the quiz array
            LoadQuizQuestions();
        }

    
        // Adds a timestamped entry to the session's activity log. 
        // Caps the list at 10 items to prevent memory bloat during long sessions.
    
        private void LogActivity(string action)
        {
            // Remove the oldest entry if we hit the limit
            if (_activityLog.Count >= 10) _activityLog.RemoveAt(0);
            _activityLog.Add($"[{DateTime.Now:HH:mm}] {action}");
        }

        // --- DATABASE BRIDGE METHODS ---
        // These methods allow the UI to interact with the database indirectly through the BotEngine
        public List<UserTaskModel> GetUserTasks() => _dbHelper.GetTaskModels();
        public void CompleteTask(int id) { _dbHelper.MarkTaskCompleteById(id); LogActivity($"Marked Task #{id} as complete via Dashboard."); }
        public void DeleteTask(int id) { _dbHelper.DeleteTaskById(id); LogActivity($"Deleted Task #{id} via Dashboard."); }

    
        // Returns the active quiz question object if a quiz is running; otherwise, returns null.
    
        public QuizQuestion? GetCurrentQuizQuestion() => IsQuizActive && _currentQuestionIndex < _quizQuestions.Count ? _quizQuestions[_currentQuestionIndex] : null;

    
        // The main Natural Language Processing (NLP) router. 
        // Takes the raw user string, applies Regex rules, and determines the appropriate output.
    
        // <param name="userInput">The raw text entered by the user.</param>
        // <returns>The string response generated by the bot.</returns>
        public string ProcessInput(string? userInput)
        {
            // Edge case: Ignore empty submissions unless we are in Quiz mode (which relies on button clicks)
            if (string.IsNullOrWhiteSpace(userInput) && !IsQuizActive) return "I didn't quite catch that.";

            string normalizedInput = userInput?.Trim() ?? "";

            // If a quiz is currently running, hijack the input process and route it straight to the Quiz Handler
            if (_currentState == BotState.QuizActive) return HandleQuizInput(normalizedInput);

            // Convert to lowercase to make regex and keyword matching easier
            string lowerInput = normalizedInput.ToLower();

            // Check if the user is asking to view their session history
            if (Regex.IsMatch(lowerInput, @"\b(activity log|what have you done)\b"))
            {
                LogActivity("User requested to view the activity log.");
                return GetActivityLog();
            }

            // Check if the user is triggering the quiz mini-game
            if (Regex.IsMatch(lowerInput, @"\b(start quiz|play game|take quiz)\b"))
            {
                _currentState = BotState.QuizActive; // Lock the UI into quiz mode
                _quizScore = 0;
                _currentQuestionIndex = 0;
                LogActivity("Cybersecurity Quiz started.");
                return $"Awesome! Let's test your knowledge. I'll ask you {_quizQuestions.Count} questions.\n\nQuestion 1: {_quizQuestions[0].QuestionText}";
            }

            // --- NLP REGEX PATTERN 1: Absolute Dates ---
            // Example: "remind me to update my firewall on the 30th"
            // Captures the task description in Group 1, and the numeric day in Group 2
            Match absoluteDateMatch = Regex.Match(lowerInput, @"(?:add task|set reminder|remind me)(?: to)? (.+?) on the (\d{1,2})(?:st|nd|rd|th)");
            if (absoluteDateMatch.Success)
            {
                string taskExtract = absoluteDateMatch.Groups[1].Value.Trim();
                // Capitalize the first letter for neatness in the UI
                if (taskExtract.Length > 0) taskExtract = char.ToUpper(taskExtract[0]) + taskExtract.Substring(1);

                int targetDay = int.Parse(absoluteDateMatch.Groups[2].Value);
                DateTime now = DateTime.Now;
                DateTime reminderDate;

                try
                {
                    // Attempt to map the requested day to the current year and month
                    reminderDate = new DateTime(now.Year, now.Month, targetDay);

                    // Smart adjustment: If that day has already passed this month, bump the reminder to next month
                    if (reminderDate.Date <= now.Date)
                    {
                        reminderDate = reminderDate.AddMonths(1);
                    }
                }
                catch (ArgumentOutOfRangeException)
                {
                    // Exception occurs if the user asks for a day that doesn't exist (e.g., February 31st)
                    return "I couldn't set that reminder. Please check that the day you asked for actually exists in the current month!";
                }

                _dbHelper.AddUserTask(taskExtract, "Task added via smart chat.", reminderDate);
                LogActivity($"Task added: '{taskExtract}'");
                return $"Got it! I've added '{taskExtract}' and set your reminder for {reminderDate.ToShortDateString()}.";
            }

            // --- NLP REGEX PATTERN 2: Relative Dates ---
            // Example: "remind me to check logs in 3 days"
            // Captures the amount of days in Group 1 (optional), and the task description in Group 2
            Match relativeDateMatch = Regex.Match(lowerInput, @"(?:add task|set reminder|remind me)(?: in (\d+) days?)?(?: to)? (.+)");
            if (relativeDateMatch.Success)
            {
                string daysString = relativeDateMatch.Groups[1].Value;
                string taskExtract = relativeDateMatch.Groups[2].Value.Trim();

                // Capitalize the first letter
                if (taskExtract.Length > 0) taskExtract = char.ToUpper(taskExtract[0]) + taskExtract.Substring(1);

                // Default to tomorrow (1 day) if the user didn't specify a timeframe
                int daysToAdd = string.IsNullOrEmpty(daysString) ? 1 : int.Parse(daysString);
                DateTime reminderDate = DateTime.Now.AddDays(daysToAdd);

                _dbHelper.AddUserTask(taskExtract, "Task added via smart chat.", reminderDate);
                LogActivity($"Task added: '{taskExtract}'");
                return $"Got it! I've added '{taskExtract}' and set your reminder for {reminderDate.ToShortDateString()}.";
            }

            // --- UI CONTROL COMMAND ---
            // Intercepts requests to view tasks and returns a hidden system token.
            // The MainWindow.xaml.cs reads this token and opens the visual dashboard instead of printing text.
            if (Regex.IsMatch(lowerInput, @"\b(show|tell|what|view).*?(tasks|reminders)\b"))
            {
                LogActivity("User opened the Interactive Task Dashboard.");
                return "[DISPLAY_TASKS]";
            }

            // --- KNOWLEDGE BASE FALLBACK ---
            // If it wasn't a command, check if the user is asking about a known cybersecurity topic
            SentimentModifier? sentimentModifier = DetectSentiment(lowerInput);
            foreach (var topic in _topicResponses.Keys)
            {
                if (lowerInput.Contains(topic))
                {
                    // Select a random response from the array associated with the matched keyword
                    string baseResponse = _topicResponses[topic][_randomizer.Next(_topicResponses[topic].Count)];
                    LogActivity($"Provided info about '{topic}'.");

                    // Apply sentiment modulation if the delegate exists (e.g., sound more urgent if user is hacked)
                    return sentimentModifier != null ? sentimentModifier(baseResponse) : baseResponse;
                }
            }

            // Absolute Fallback: Reached if no regex or keywords trigger
            return "I'm not sure I understand. You can ask me to 'start quiz', 'remind me to [action] on the 15th', 'show tasks', or ask about scams.";
        }

    
        // Formats the volatile List memory into a readable multiline string.
    
        private string GetActivityLog()
        {
            if (_activityLog.Count == 0) return "I haven't done much yet today!";

            string logString = "Here's a summary of recent actions:\n";
            for (int i = 0; i < _activityLog.Count; i++) logString += $"{i + 1}. {_activityLog[i]}\n";

            return logString;
        }

    
        // Hardcodes the cybersecurity knowledge base questions into memory.
    
        private void LoadQuizQuestions()
        {
            _quizQuestions = new List<QuizQuestion>
            {
                new QuizQuestion("What should you do if you receive an unexpected email asking for your password?", new List<string> { "Reply with it", "Delete it", "Report as phishing", "Ignore it" }, "Report as phishing", "Reporting phishing emails helps prevent scams and alerts security teams."),
                new QuizQuestion("True or False: Using 'Password123' is a secure choice.", new List<string> { "True", "False" }, "False", "Weak passwords are easily cracked. Always use a mix of characters, numbers, and symbols."),
                new QuizQuestion("What does 2FA stand for?", new List<string> { "Two-File Access", "Two-Factor Authentication", "To Find Accounts" }, "Two-Factor Authentication", "2FA adds an extra layer of security beyond just your password."),
                new QuizQuestion("True or False: Public Wi-Fi is safe for online banking.", new List<string> { "True", "False" }, "False", "Public networks can be easily intercepted by hackers. Avoid sensitive transactions on them."),
                new QuizQuestion("What type of malware locks your files until you pay a fee?", new List<string> { "Spyware", "Adware", "Ransomware" }, "Ransomware", "Ransomware encrypts your data and demands money for the decryption key."),
                new QuizQuestion("Why should you update your phone and PC software regularly?", new List<string> { "To get new emojis", "To patch security vulnerabilities", "To use more battery" }, "To patch security vulnerabilities", "Updates often contain critical patches for newly discovered security flaws."),
                new QuizQuestion("What is a VPN primarily used for?", new List<string> { "Speeding up the internet", "Encrypting your internet connection", "Blocking ads" }, "Encrypting your internet connection", "A Virtual Private Network (VPN) encrypts your data, keeping your browsing private."),
                new QuizQuestion("What is the main purpose of a firewall?", new List<string> { "To block unauthorized network access", "To cool down your CPU", "To store passwords" }, "To block unauthorized network access", "Firewalls act as a barrier between your internal network and external threats."),
                new QuizQuestion("True or False: You should use the same password for all your accounts so you don't forget it.", new List<string> { "True", "False" }, "False", "If one account is breached, all your accounts are compromised. Always use unique passwords."),
                new QuizQuestion("What is it called when an attacker manipulates you into giving up confidential info?", new List<string> { "Social Engineering", "Hacking", "Brute Forcing" }, "Social Engineering", "Social engineering relies on human interaction and psychological manipulation rather than pure technical exploits."),
                new QuizQuestion("If a website URL starts with HTTPS, what does the 'S' stand for?", new List<string> { "System", "Secure", "Server" }, "Secure", "HTTPS means the connection between your browser and the website is encrypted and secure.")
            };
        }

    
        // Evaluates a user's answer against the active QuizQuestion, increments the score, and returns formatting feedback.
    
        // <param name="selectedAnswer">The raw text of the button the user clicked.</param>
        private string HandleQuizInput(string selectedAnswer)
        {
            var currentQuestion = _quizQuestions[_currentQuestionIndex];

            // Uses OrdinalIgnoreCase so we don't fail due to casing differences in the UI buttons
            bool isCorrect = selectedAnswer.Equals(currentQuestion.CorrectAnswer, StringComparison.OrdinalIgnoreCase);

            // Construct the feedback string using a ternary operator
            string feedback = isCorrect ? "✅ Correct!" : $"❌ Incorrect. The right answer was: {currentQuestion.CorrectAnswer}.";
            feedback += $" {currentQuestion.Explanation}\n\n";

            if (isCorrect) _quizScore++;
            _currentQuestionIndex++;

            // Detect if the array is exhausted (Quiz over)
            if (_currentQuestionIndex >= _quizQuestions.Count)
            {
                _currentState = BotState.Normal; // Unlock the main chat input
                return feedback + $"--- Quiz Finished! ---\nYou scored {_quizScore} out of {_quizQuestions.Count}.";
            }

            // Send the next question
            return feedback + $"Question {_currentQuestionIndex + 1}: {_quizQuestions[_currentQuestionIndex].QuestionText}";
        }

        // Future placeholder: Returns a method that modifies a string based on detected sentiment.
        private SentimentModifier? DetectSentiment(string input) { return null; }
    }


    // A structured model representing a single quiz question.

    public class QuizQuestion
    {
        public string QuestionText { get; set; }

        // Stored as a list so the WPF UI can dynamically render a variable amount of buttons
        public List<string> Options { get; set; }

        public string CorrectAnswer { get; set; }

        // Contextual learning feedback provided to the user after they answer
        public string Explanation { get; set; }

        public QuizQuestion(string question, List<string> options, string answer, string explanation)
        {
            QuestionText = question;
            Options = options;
            CorrectAnswer = answer;
            Explanation = explanation;
        }
    }
}